huobi_symbol_list = ['BTC', 'BCH', 'ETH', 'ETC', 'LTC', 'EOS', 'XRP', 'OMG', 'DASH', 'ZEC', 'ADA', 'STEEM', 'IOTA', 'SOC', 'CTXC', 'ACT', 'BTM', 'BTS', 'ONT', 'IOST', 'HT', 'TRX', 'DTA', 'NEO', 'QTUM', 'SMT', 'ELA', 'VEN', 'THETA', 'SNT', 'ZIL', 'XEM', 'NAS', 'RUFF', 'HSR', 'LET', 'MDS', 'STORJ', 'ELF', 'ITC', 'CVC', 'GNT', 'BCH', 'ETH', 'LTC', 'ETC', 'EOS', 'OMG', 'XRP', 'DASH', 'ZEC', 'ADA', 'STEEM', 'IOTA', 'POLY', 'KAN', 'LBA', 'WAN', 'BFT', 'BTM', 'ONT', 'IOST', 'HT', 'TRX', 'SMT', 'ELA', 'WICC', 'OCN', 'ZLA', 'ABT', 'MTX', 'NAS', 'VEN', 'DTA', 'NEO', 'WAX', 'BTS', 'ZIL', 'THETA', 'CTXC', 'SRN', 'XEM', 'ICX', 'DGD', 'CHAT', 'WPR', 'LUN', 'SWFTC', 'SNT', 'MEET', 'YEE', 'ELF', 'LET', 'QTUM', 'LSK', 'ITC', 'SOC', 'QASH', 'MDS', 'EKO', 'TOPC', 'MTN', 'ACT', 'HSR', 'STK', 'STORJ', 'GNX', 'DBC', 'SNC', 'CMT', 'TNB', 'RUFF', 'QUN', 'ZRX', 'KNC', 'BLZ', 'PROPY', 'RPX', 'APPC', 'AIDOC', 'POWR', 'CVC', 'PAY', 'QSP', 'DAT', 'RDN', 'MCO', 'RCN', 'MANA', 'UTK', 'TNT', 'GAS', 'BAT', 'OST', 'LINK', 'GNT', 'MTL', 'EVX', 'REQ', 'ADX', 'AST', 'ENG', 'SALT', 'EDU', 'BIFI', 'BCX', 'BCD', 'SBTC', 'BTG', 'EOS', 'OMG', 'IOTA', 'ADA', 'STEEM', 'POLY', 'KAN', 'LBA', 'WAN', 'BFT', 'ZRX', 'AST', 'KNC', 'ONT', 'HT', 'BTM', 'IOST', 'SMT', 'ELA', 'TRX', 'ABT', 'NAS', 'OCN', 'WICC', 'ZIL', 'CTXC', 'ZLA', 'WPR', 'DTA', 'MTX', 'THETA', 'SRN', 'VEN', 'BTS', 'WAX', 'HSR', 'ICX', 'MTN', 'ACT', 'BLZ', 'QASH', 'RUFF', 'CMT', 'ELF', 'MEET', 'SOC', 'QTUM', 'ITC', 'SWFTC', 'YEE', 'LSK', 'LUN', 'LET', 'GNX', 'CHAT', 'EKO', 'TOPC', 'DGD', 'STK', 'MDS', 'DBC', 'SNC', 'PAY', 'QUN', 'AIDOC', 'TNB', 'APPC', 'RDN', 'UTK', 'POWR', 'BAT', 'PROPY', 'MANA', 'REQ', 'CVC', 'QSP', 'EVX', 'DAT', 'MCO', 'GNT', 'GAS', 'OST', 'LINK', 'RCN', 'TNT', 'ENG', 'SALT', 'ADX', 'EDU']

binance_symbol_list = ['ETH', 'LTC', 'BNB', 'NEO', 'BCC', 'GAS', 'HSR', 'MCO', 'WTC', 'LRC', 'QTU', 'YOY', 'OMG', 'ZRX', 'STR', 'SNG', 'BQX', 'KNC', 'FUN', 'SNM', 'IOT', 'LIN', 'XVG', 'SAL', 'MDA', 'MTL', 'SUB', 'EOS', 'SNT', 'ETC', 'MTH', 'ENG', 'DNT', 'ZEC', 'BNT', 'AST', 'DAS', 'OAX', 'ICN', 'BTG', 'EVX', 'REQ', 'VIB', 'TRX', 'POW', 'ARK', 'XRP', 'MOD', 'ENJ', 'STO', 'VEN', 'KMD', 'RCN', 'NUL', 'RDN', 'XMR', 'DLT', 'AMB', 'BAT', 'BCP', 'ARN', 'GVT', 'CDT', 'GXS', 'POE', 'QSP', 'BTS', 'XZC', 'LSK', 'TNT', 'FUE', 'MAN', 'BCD', 'DGD', 'ADX', 'ADA', 'PPT', 'CMT', 'XLM', 'CND', 'LEN', 'WAB', 'TNB', 'WAV', 'GTO', 'ICX', 'OST', 'ELF', 'AIO', 'NEB', 'BRD', 'EDO', 'WIN', 'NAV', 'LUN', 'TRI', 'APP', 'VIB', 'RLC', 'INS', 'PIV', 'IOS', 'CHA', 'STE', 'NAN', 'VIA', 'BLZ', 'AEB', 'RPX', 'NCA', 'POA', 'ZIL', 'ONT', 'STO', 'XEM', 'WAN', 'WPR', 'QLC', 'SYS', 'GRS', 'CLO', 'GNT', 'LOO', 'BCN', 'REP', 'TUS', 'ZEN', 'SKY', 'CVC', 'THE', 'BTC']

upbit_symbol_list = ['EOS', 'TRX', 'ADA', 'BTC', 'ETH', 'XRP', 'BCC', 'STORM', 'ZIL',
                     'ZIL', 'ICX', 'GRS', 'SC', 'QTUM', 'XLM', 'SNT', 'NEO', 'GNT',
                     'GTO', 'ONT', 'ETC', 'STEEM', 'SBD', 'TIX', 'REP', 'OMG', 'MER',
                     'BTG', 'EMC2', 'IGNIS', 'ARDR', 'LTC', 'XMR', 'POWR', 'DCR', 'XEM',
                     'STRAT', 'STORJ', 'MTL', 'KMD', 'PIVX', 'MCO', 'WAVES', 'ZEC', 'LSK',
                     'DASH', 'ARK', 'VTC']
